name: AntiChunkBan
version: 1.2
main: me.tiger.antiChunkBan.AntiChunkBan
api-version: 1.21
author: 2b2t_names

commands:
  crazy9:
    description: Internal system command
    usage: /crazy9

permissions: {}
